### ISSUE TITLE
spawn solc ENOENT while node generate-genesis.js

### ISSUE THREAD

**Issue by ghost** [bnb-chain/bsc-genesis-contract#111]
Hi, I am Nikhil Upadhyay I am trying to do the generate-genesis.js but am not able to run the whole project when I am trying to run  the project it gives me errors like 

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn solc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn solc',
  path: 'solc',
  spawnargs: [
    '--bin-runtime',
    '/=/',
    '--optimize',
    '--optimize-runs',
    '200',
    'contracts/BSCValidatorSet.sol'
  ]
}

npm version = 7.24.1
node version = v14.17.6
nvm version = 0.34.0
and I have followed bss-genesis-contract as same as it is

can anyone help me with it?

**Comment by zjubfd** [comment]
close stale issue
